name: run all questions script and create tables in staging
on: 
  push:
    branches:
      - dev/*
jobs:
  connect-to-gcp-and-write-table-in-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Run checkout@v3 as dependency for Google Cloud Auth'
        uses: 'actions/checkout@v3'
        
      - id:   'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: 'Install requirements from requirements.txt'
        run: pip install -r requirements.txt

      - name: 'Get changed files'
        id:   'changed-files'
        uses: tj-actions/changed-files@v35

      - name: 'Get all changed question files'
        id:   'changed-files-specific'
        uses: tj-actions/changed-files@v35
        with:
          files: | 
            questions/*.py 

      - name: 'Run question 1 staging job in Python file'
        if:   steps.changed-files-specific.outputs.any_changed == 'true'
        run:  python questions/question_1_script.py

      - name: 'Run question 2 staging job in Python file'
        if:   steps.changed-files-specific.outputs.any_changed == 'true'
        run:  python questions/question_2_script.py

      - name: 'Run question 3 staging job in Python file'
        if:   steps.changed-files-specific.outputs.any_changed == 'true'
        run:  python questions/question_3_script.py

      - name: 'Run tests on staging tables'
        run:  pytest tests/test_questions.py