name: create tables in production on merge to main
run-name: testing merge to main and creating production tables ${{ github.actor }} 🚀
on: 
  push:
    branches:
      - dev/refactoring-for-d-r-y-modularity
jobs:
  connect-to-gcp-and-write-table-in-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Run checkout@v3 as dependency for Google Cloud Auth'
        uses: 'actions/checkout@v3'
        
      - id:   'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: 'Install requirements from requirements.txt'
        run: pip install -r requirements.txt

      - name: 'Run tests on staging tables'
        run:  pytest tests/test_questions.py

      - name: 'Copy tables over to main - placeholder, currently passes'
        run:  python questions/production.py