name: run all questions script and create tables in staging
on: 
  push:
    branches:
      - dev/*
jobs:
  connect-to-gcp-and-write-table-in-staging:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Run checkout@v3 as dependency for Google Cloud Auth'
        uses: 'actions/checkout@v3'
        
      - id:   'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Setup Python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: 'Install requirements from requirements.txt'
        run: pip install -r requirements.txt

      - name: 'Run question 1 staging job in Python file'
        run:  python question_1_script.py

      - name: 'Run question 2 staging job in Python file'
        run:  python question_2_script.py